# A Docker Swarm file to

version: "3"

enviroment:
  - DATABASE_NAME=sms
  - DATABASE_USER=sms_user
  - DATABASE_PASSWORD=sms_password
  - DATABASE_HOST=postgres_db
  - DATABASE_PORT=5432
  - REDIS_HOST=redis
  - REDIS_PORT=6379
  - REDIS_DB_NUM=0
  - TZ=Europe/Moscow

volumes:
  postgres_volume:
  static_volume:

services:

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:5432  # todo remove

  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379  # todo remove

  sms_app:
    image: sms_app
    depends_on:
      - postgres_db
      - redis
    environment:
      - DEBUG=False
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=${DATABASE_USER}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_HOST=${DATABASE_HOST}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB_NUM=${REDIS_DB_NUM}
      - TIME_ZONE=${TZ}
      links:
        - postgres_db
        - redis
      ports:
        - 8001:8001  # todo remove
        - 5555:5555
      entrypoint: ./run.sh

  nginx:
    image: nginx
    depends_on:
      - sms_app
    ports:
      - 80:80